apiVersion: v1
kind: Service
metadata:
  name: argocd-external
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
  - port: 80