apiVersion: v1
kind: Service
metadata:
  name: twodo-backend-service
  labels:
    {{- include "twodo-chart.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      name: http
  selector:
    app: {{ .Values.backend.name }}
    