apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: prometheus-stack-grafana.monitoring.svc.cluster.local
  ports:
  - port: 80