apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ .Values.backend.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.backend.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.backend.database.password }}
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.database.host }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432